2024-12-19 15:01:13 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 15:01:13 - INFO - Migrando perfis para a pasta default...
2024-12-19 15:01:13 - INFO - Migração de perfis concluída
2024-12-19 15:01:13 - INFO - Migrando comentários para a pasta default...
2024-12-19 15:01:13 - INFO - Migração de comentários concluída
2024-12-19 15:01:14 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 15:03:15 - ERROR - Erro de validação: O número de comentários deve ser igual ao número de perfis selecionados.
2024-12-19 15:13:32 - INFO - Pasta 'tweste' criada com sucesso para profiles
2024-12-19 16:11:15 - INFO - Pasta 'tweste' removida com sucesso de profiles
2024-12-19 16:55:46 - ERROR - Erro ao carregar página de edição: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 821, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 83, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 16:55:46 - ERROR - Erro ao verificar licença: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
2024-12-19 16:58:39 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 17:02:49 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 17:03:46 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 17:05:31 - ERROR - Erro ao carregar página de edição: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 821, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 83, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 17:05:31 - ERROR - Erro ao verificar licença: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
2024-12-19 18:34:41 - ERROR - Erro ao carregar página inicial: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 549, in index
    return render_template('index.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\index.html", line 253, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

2024-12-19 18:34:41 - ERROR - Erro ao verificar licença: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2024-12-19 18:52:33 - ERROR - Erro ao carregar página de edição: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 821, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 18:52:33 - ERROR - Erro ao verificar licença: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
2024-12-19 19:03:01 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:04:18 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:05:28 - ERROR - Erro ao carregar página de edição: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 825, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:05:28 - ERROR - Erro ao verificar licença: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
2024-12-19 19:06:19 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:07:21 - ERROR - Erro ao carregar página de edição: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 825, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:07:21 - ERROR - Erro ao verificar licença: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
2024-12-19 19:09:31 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:12:40 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:13:53 - ERROR - Erro ao carregar página de edição: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 838, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:24:32 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:25:58 - ERROR - Erro ao carregar dados: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 838, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:26:38 - INFO - Nova instância do Chrome 0 iniciada para processar 1 comentários
2024-12-19 19:26:38 - WARNING - Perfil juliana abreu não encontrado
2024-12-19 19:26:38 - INFO - Instância do Chrome 0 fechada com sucesso
2024-12-19 19:26:40 - INFO - Diretório temporário da instância 0 removido com sucesso na tentativa 1
2024-12-19 19:27:00 - INFO - Nova instância do Chrome 0 iniciada para processar 1 comentários
2024-12-19 19:27:00 - WARNING - Perfil leticia juliana não encontrado
2024-12-19 19:27:00 - INFO - Instância do Chrome 0 fechada com sucesso
2024-12-19 19:27:03 - INFO - Diretório temporário da instância 0 removido com sucesso na tentativa 1
2024-12-19 19:42:05 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:43:05 - INFO - Nova instância do Chrome 0 iniciada para processar 1 comentários
2024-12-19 19:43:05 - ERROR - Erro ao processar comentário: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 413, in process_comment_batch
    selected_profile_folder = request.args.get('profile_folder', 'default')
                              ^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\local.py", line 519, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.
 para brenda lais
2024-12-19 19:43:05 - ERROR - Erro na instância do Chrome 0: cannot access local variable 'profile_data' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 413, in process_comment_batch
    selected_profile_folder = request.args.get('profile_folder', 'default')
                              ^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\local.py", line 519, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request. Consult the documentation on testing for
information about how to avoid this problem.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 499, in process_comment_batch
    registrar_erro(profile_data['email'], erro)
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'profile_data' where it is not associated with a value

2024-12-19 19:43:06 - INFO - Instância do Chrome 0 fechada com sucesso
2024-12-19 19:43:08 - INFO - Diretório temporário da instância 0 removido com sucesso na tentativa 1
2024-12-19 19:43:08 - ERROR - Erro em um dos lotes de comentários: cannot access local variable 'profile_data' where it is not associated with a value
2024-12-19 19:43:35 - ERROR - Erro ao carregar dados: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 839, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:45:12 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:45:46 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-19 19:52:02 - INFO - Nova instância do Chrome 0 iniciada para processar 1 comentários
2024-12-19 19:52:02 - INFO - Processando comentário para perfil: leticia juliana
2024-12-19 19:52:35 - INFO - Comentário enviado com sucesso para o perfil leticia juliana
2024-12-19 19:52:35 - INFO - Instância do Chrome 0 fechada com sucesso
2024-12-19 19:52:38 - INFO - Diretório temporário da instância 0 removido com sucesso na tentativa 1
2024-12-19 19:52:51 - ERROR - Erro ao carregar dados: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 839, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:53:53 - ERROR - Erro ao carregar dados: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 839, in edit_remove
    return render_template('edit_remove.html',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\templates\edit_remove.html", line 88, in block 'content'
    <form action="{{ url_for('move_to_folder') }}" method="post" class="ms-3">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'move_to_folder'. Did you mean 'remove_folder' instead?

2024-12-19 19:57:08 - INFO - Sistema de licenças inicializado com API: CommentTikPro
2024-12-20 01:32:31 - INFO - Nova instância do Chrome 0 iniciada para processar 1 comentários
2024-12-20 01:32:31 - INFO - Processando comentário para perfil: Juana bela
2024-12-20 01:33:05 - INFO - Comentário enviado com sucesso para o perfil Juana bela
2024-12-20 01:33:05 - INFO - Instância do Chrome 0 fechada com sucesso
2024-12-20 01:33:08 - INFO - Diretório temporário da instância 0 removido com sucesso na tentativa 1
2024-12-20 01:53:30 - INFO - Nova instância do Chrome 0 iniciada para processar 1 comentários
2024-12-20 01:53:30 - INFO - Processando comentário para perfil: luan pedro
2024-12-20 01:53:32 - INFO - Nova instância do Chrome 1 iniciada para processar 1 comentários
2024-12-20 01:53:32 - INFO - Processando comentário para perfil: Caio Pimentel
2024-12-20 01:54:04 - INFO - Comentário enviado com sucesso para o perfil luan pedro
2024-12-20 01:54:04 - INFO - Instância do Chrome 0 fechada com sucesso
2024-12-20 01:54:07 - INFO - Diretório temporário da instância 0 removido com sucesso na tentativa 1
2024-12-20 01:54:08 - WARNING - Caixa de comentário não encontrada para https://www.tiktok.com/@vivianeluana14/video/7416838342504992005
2024-12-20 01:54:08 - ERROR - Erro ao processar comentário: 'email'
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 449, in process_comment_batch
    comment_box = WebDriverWait(driver, 10).until(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x006FEC13+23731]
	(No symbol) [0x0068C394]
	(No symbol) [0x0056BE63]
	(No symbol) [0x005AFCE6]
	(No symbol) [0x005AFF2B]
	(No symbol) [0x005ED892]
	(No symbol) [0x005D1EA4]
	(No symbol) [0x005EB46E]
	(No symbol) [0x005D1BF6]
	(No symbol) [0x005A3F35]
	(No symbol) [0x005A4EBD]
	GetHandleVerifier [0x009DF0D3+3039603]
	GetHandleVerifier [0x009F2DEA+3120778]
	GetHandleVerifier [0x009EB592+3089970]
	GetHandleVerifier [0x007943B0+635984]
	(No symbol) [0x00694DCD]
	(No symbol) [0x00692068]
	(No symbol) [0x00692205]
	(No symbol) [0x00684FD0]
	BaseThreadInitThunk [0x75DD7BA9+25]
	RtlInitializeExceptionChain [0x77E6C0CB+107]
	RtlClearBits [0x77E6C04F+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 455, in process_comment_batch
    registrar_erro(profile_data['email'], erro)
                   ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'email'
 para Caio Pimentel
2024-12-20 01:54:08 - ERROR - Erro na instância do Chrome 1: 'email'
Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 449, in process_comment_batch
    comment_box = WebDriverWait(driver, 10).until(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ggpaz\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x006FEC13+23731]
	(No symbol) [0x0068C394]
	(No symbol) [0x0056BE63]
	(No symbol) [0x005AFCE6]
	(No symbol) [0x005AFF2B]
	(No symbol) [0x005ED892]
	(No symbol) [0x005D1EA4]
	(No symbol) [0x005EB46E]
	(No symbol) [0x005D1BF6]
	(No symbol) [0x005A3F35]
	(No symbol) [0x005A4EBD]
	GetHandleVerifier [0x009DF0D3+3039603]
	GetHandleVerifier [0x009F2DEA+3120778]
	GetHandleVerifier [0x009EB592+3089970]
	GetHandleVerifier [0x007943B0+635984]
	(No symbol) [0x00694DCD]
	(No symbol) [0x00692068]
	(No symbol) [0x00692205]
	(No symbol) [0x00684FD0]
	BaseThreadInitThunk [0x75DD7BA9+25]
	RtlInitializeExceptionChain [0x77E6C0CB+107]
	RtlClearBits [0x77E6C04F+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 455, in process_comment_batch
    registrar_erro(profile_data['email'], erro)
                   ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ggpaz\Desktop\sistema comentarios atualizar\versão com servidor desatualizado\automação\app.py", line 498, in process_comment_batch
    registrar_erro(profile_data['email'], erro)
                   ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'email'

2024-12-20 01:54:08 - INFO - Instância do Chrome 1 fechada com sucesso
2024-12-20 01:54:11 - INFO - Diretório temporário da instância 1 removido com sucesso na tentativa 1
2024-12-20 01:54:11 - ERROR - Erro em um dos lotes de comentários: 'email'
2024-12-20 01:57:04 - INFO - Iniciando processo de encerramento do servidor
2024-12-20 01:58:01 - INFO - Máquina liberada e usuário realizou logout com sucesso
2024-12-20 01:58:59 - INFO - Iniciando processo de encerramento do servidor
